namespace Scraping.Common
{
    public class VillagerLanguageNames
    {
        public Dictionary<string, string> Villagers { get; }

        public VillagerLanguageNames()
        {
            Villagers = new Dictionary<string, string>
            {
                { "EN", "Alex" },
                { "ES", "Alex" },
                { "FR", "Alex" },
                { "PT", "Alex" },
                { "DE", "Alex" },
                { "JA", "アレックス"},
                { "EN", "Elliott" },
                { "ES", "Elliott" },
                { "FR", "Elliott" },
                { "PT", "Elliott" },
                { "DE", "Elliott" },
                { "JA", "エリオット"},
                { "EN", "Harvey"},
                { "ES", "Harvey"},
                { "FR", "Harvey"},
                { "PT", "Harvey"},
                { "DE", "Harvey"},
                { "JA", "ハーヴィー"},
                { "EN", "Sam"},
                { "ES", "Sam"},
                { "FR", "Sam"},
                { "PT", "Sam"},
                { "DE", "Sam"},
                { "JA", "サム"},
                { "EN", "Sebastian"},
                { "ES", "Sebastian"},
                { "FR", "Sebastian"},
                { "PT", "Sebastian"},
                { "DE", "Sebastian"},
                { "JA", "セバスチャン"},
                { "EN", "Shane"},
                { "ES", "Shane"},
                { "FR", "Shane"},
                { "PT", "Shane"},
                { "DE", "Shane"},
                { "JA", "シェーン"},
                { "EN", "Abigail"},
                { "ES", "Abigail"},
                { "FR", "Abigail"},
                { "PT", "Abigail"},
                { "DE", "Abigail"},
                { "JA", "アビゲイル"},
                { "EN", "Emily"},
                { "ES", "Emily"},
                { "FR", "Emily"},
                { "PT", "Emily"},
                { "DE", "Emily"},
                { "JA", "エミリー"},
                { "EN", "Haley"},
                { "ES", "Haley"},
                { "FR", "Haley"},
                { "PT", "Haley"},
                { "DE", "Haley"},
                { "JA", "ヘイリー"},
                { "EN", "Leah"},
                { "ES", "Leah"},
                { "FR", "Leah"},
                { "PT", "Leah"},
                { "DE", "Leah"},
                { "JA", "リア" },
                { "EN", "Maru"},
                { "ES", "Maru"},
                { "FR", "Maru"},
                { "PT", "Maru"},
                { "DE", "Maru"},
                { "JA", "マル" },
                { "EN", "Penny"},
                { "ES", "Penny"},
                { "FR", "Penny"},
                { "PT", "Penny"},
                { "DE", "Penny"},
                { "JA", "ペニー"},
            };
        }
    }
}